"""Named ticker universes for targeted bot runs."""

from __future__ import annotations


CURATED_SYMBOLS = """
NVDA AVGO GOOGL MSFT AMZN META PENG OSS SMCI PSTG NTAP ANET CSCO ORCL PLTR AI BBAI SOUN PATH SNOW DDOG MDB GTLB
VRT MOD AMD INTC ARM MU WDC STM MCHP ON WOLF AXTI HIMX MKSI ASML LRCX AMAT KLAC TSM QCOM TXN ADI MRVL MPWR SWKS
QRVO TER OKLO BE CEG VST TLN SMR FLR GE LITE POWL BW PL F STZ ENPH SEDG FSLR NEE NRG ET EPD XOM CVX BTU
SHOP PINS TYL CSGP SAP CRWD PANW FTNT NET OKTA ZS MRNA GNRC GLW HOOD COIN PYPL MELI SE UBER LYFT ABNB DASH
TOYO STX TPL FIX ETN PH EMR ROK HUBB JCI CMI CAT PWR EXPO ACM VMC MLM URI GFF LECO LEN DHI BLD EXP AOS CIEN
COHR EQIX DLR IRM AMT CCI SBAC VZ T TMUS LUMN FFIV AKAM EGHT RNG BAND TWLO CRNC VIAV EXTR ADTN DGII SHAK
RKLB LUNR HII LMT NOC GD LHX RTX BWXT ISRG SYM AMRC SPR TDG HEI HXL IRDM BCO AVAV KTOS NCNO CRSR LOGI
RGTI QBTS IONQ LLY NVO REGN VRTX ILMN TMO A WST RMD DXCM PODD EW SYK MDT BSX BDX IQV MEDP CRL TECH EXAS GH CRM
NOW ADBE INTU WDAY TEAM SNPS CDNS PTC HUBS DT ESTC NTNX TOST CFLT S PAYC PCTY BILL DOCU DBX BOX ASAN
AAPL TSLA NFLX DIS SONY NTES BIDU BABA JD PDD CPNG BKNG EXPE TRIP MAR H HLT RCL CCL NCLH LUV DAL UAL AAL ALK
V MA AXP COF JPM BAC GS MS BLK BX KKR APO CG SOFI NU FI FIS GPN JKHY IBKR SCHW LPLA TROW AMP NKE LULU DECK
CROX ONON BIRK ANF ELF ULTA TPR CPRI LEVI TJX ROST DLTR DG TGT WMT COST HD LOW TSCO ORLY AZO NXPI LSCC DIOD
POWI RMBS ACLS AEIS AMKR FORM INFA NVMI PDFS SITM SMTC SYNA UCTT VECO IPGP ONTO CAMT ASYS INDI AOSL CEVA
MRK PFE BMY JNJ ABBV AMGN GILD BIIB ALNY BMRN INCY BNTX CRSP BEAM NTLA EDIT TWST IOVA SRPT AXSM
KNSA VCYT HON MMM BA AXON DE AGCO TEX OSK PCAR KMT SNA SWK FTV IR GGG DOV XYL FELE TOL KBH MTH PHM TMHC CCS
COP EOG OXY DVN FANG APA HAL SLB BKR NOV MPC PSX VLO KMI WMB OKE LNG TRGP PAA MPLX WES HESM AM FCX SCCO
NEM GOLD AA CENX NUE STLD CLF RS MP LAC ALB SQM FMC CTVA CF MOS NTR APD LIN ECL SHW PPG RPM RBLX EA TTWO WBD
ROKU SPOT IMAX CNK NYT SCHL NXST TGNA AMCX TKO MANU MSGE LYV CZR PLD PSA
EXR CUBE O VNO SPG REG KIM BXP SLG ARE MPW WELL VTR AVB EQR MAA CPT EXPD FDX UPS CHRW JBHT ODFL SAIA XPO
KNX ARCB LSTR UNP NSC CSX CP CNI GM RIVN LCID QS STLA TM HMC RACE LI NIO XPEV HOG LEA MGA
"""


WATCHLISTS = {
    "curated": CURATED_SYMBOLS,
}
